spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sfedu-database
    username: postgres
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: false